package edu.ucsb.nceas.osti_elink;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.w3c.dom.Document;

/**
 * DOIOperations provides user-facing operations for DOI management.
 */
public class DOIOperations {
    private static final String STATUS = "SUCCESS";
    private static final String SUCCESS = "SUCCESS";
    private static final String DOI = "doi";

    protected static Log log = LogFactory.getLog(DOIOperations.class);

    private OSTIElinkService ostiService;
    private MetadataManager metadataManager;
    private DOIUtilities doiUtilities;

    public DOIOperations(OSTIElinkService ostiService, MetadataManager metadataManager, DOIUtilities doiUtilities) {
        this.ostiService = ostiService;
        this.metadataManager = metadataManager;
        this.doiUtilities = doiUtilities;
    }

    /**
     * Create a new, unique, opaque identifier by requesting the OSTI elink service
     * @param siteCode  a pre-defined site code which associates doi prefixes. If it is null, the default
     * ess-dive value will be used.
     * @return  the identifier generated by OSTI for this site code
     * @throws OSTIElinkException
     */
    public String mintDOI(String siteCode) throws OSTIElinkException {
        String identifier = null;
        String minimalMetadata = doiUtilities.buildMinimalMetadata(siteCode);
        String baseApiUrl = ostiService.getBaseURL();

        log.debug("the minimal metadata is " + minimalMetadata);
        log.debug("the base url is " + baseApiUrl);

        byte[] response = ostiService.getHttpService().sendRequest(HttpService.POST, baseApiUrl, minimalMetadata);
        log.debug("DOIOperations.mintDOI - the response from the OSTI service is:\n "
                + new String(response));

        Document doc = null;
        try {
            doc = XmlUtils.generateDOM(response);
        } catch (Exception e) {
            //The response is not a xml string. We return the response as an exception
            throw new OSTIElinkException("DOIOperations.mintDOI - Error: " + new String(response));
        }
        String status = XmlUtils.getElementValue(doc, STATUS);
        String id = XmlUtils.getElementValue(doc, DOI);
        if (status != null && status.equalsIgnoreCase(SUCCESS) && id != null && !id.trim().equals("")) {
            identifier = DOI + ":" + id;
        } else {
            throw new OSTIElinkException("DOIOperations.mintDOI - Error: " + new String(response));
        }
        log.debug("DOIOperations.mintDOI - the generated identifier is " + identifier);
        return identifier;
    }

    /**
     * Get the status of a DOI. If there are multiple records for a DOI, the status of
     * the first one will be returned
     * @param doi  the doi to identify the record
     * @return  the status of the doi
     * @throws OSTIElinkException
     */
    public String getStatus(String doi) throws OSTIElinkException {
        String status = null;
        String metadata = metadataManager.getMetadata(doi);
        if (metadata == null) {
            throw new OSTIElinkException("DOIOperations.getStatus - the metadata of the DOI " + doi + " can't be found.");
        }
        Document doc = XmlUtils.generateDOM(metadata.getBytes());
        status = XmlUtils.getAttributeValue(doc, "record", "status");//get the attribute value of the first element
        log.debug("DOIOperations.getStatus - the status of " + doi + " is " + status);
        return status;
    }

    /**
     * Set new metadata to the given doi.
     * @param doi  the identifier of the object which will be set the new metadata
     * @param doiPrefix  a shortcut to determine if we can get OSTI_id (replace the query) by string comparing. The
     * safest way is pass null there (but it costs a query to the service).
     * @param metadataXML  the new metadata in xml format
     * @throws OSTIElinkException
     */
    public void setMetadata(String doi, String doiPrefix, String metadataXML) throws OSTIElinkException {
        metadataManager.setMetadata(doi, doiPrefix, metadataXML, ostiService);
    }

    /**
     * Publish a DOI with the given OSTI ID and site URL
     * @param ostiId the OSTI ID for the DOI
     * @param siteUrl the site URL where the DOI should resolve
     * @throws OSTIElinkException
     */
    public void publishDOI(String ostiId, String siteUrl) throws OSTIElinkException {
        // Implementation depends on the specific OSTI service implementation
        ostiService.handlePublishIdentifierCommand(ostiId, siteUrl);
    }
}